'''
This file stores dictionaries and other data used in the advanced hover mode 
in the main app for giving nuclear data.

Written by:
 - Joshua Wylie
'''
from dash import html

# Dictionary of possible decay mode image paths
decayImgSrc = {
    'B-':'assets/decay_modes/beta-.png',
    'B+':'assets/decay_modes/beta+.png',
    'EC':'assets/decay_modes/EC.png',
    'N':'assets/decay_modes/N.png',
    'P':'assets/decay_modes/P.png',
    '2N':'assets/decay_modes/2N.png',
    '2P':'assets/decay_modes/2P.png',
    'A':'assets/decay_modes/A.png',
    'nan':'assets/decay_modes/unknown.png',
    'Stable':'assets/decay_modes/stable4.png',
}
# Dictionary of shown information on hover for the decay mode
decayName = {
    'B-':['Decays mainly by: \u03B2',html.Sup('-'),' Decay'],
    'B+':['Decays mainly by: \u03B2',html.Sup('+'),' Decay'],
    'EC':'Decays mainly by: Electron Capture',
    'N':'Decays mainly by: Neutron Emission',
    'P':'Decays mainly by: Proton Emission',
    '2N':'Decays mainly by: 2 Neutron Emission',
    '2P':'Decays mainly by: 2 Proton Emission',
    'A':['Decays mainly by: \u03B1 Decay'],
    'nan':'Unknown Decay Mode',
    'Stable':'Stable'
}

element_symbols = {
    "Neutron(s)": "n",
    "Hydrogen": "H",
    "Helium": "He",
    "Lithium": "Li",
    "Beryllium": "Be",
    "Boron": "B",
    "Carbon": "C",
    "Nitrogen": "N",
    "Oxygen": "O",
    "Fluorine": "F",
    "Neon": "Ne",
    "Sodium": "Na",
    "Magnesium": "Mg",
    "Aluminum": "Al",
    "Silicon": "Si",
    "Phosphorus": "P",
    "Sulfur": "S",
    "Chlorine": "Cl",
    "Argon": "Ar",
    "Potassium": "K",
    "Calcium": "Ca",
    "Scandium": "Sc",
    "Titanium": "Ti",
    "Vanadium": "V",
    "Chromium": "Cr",
    "Manganese": "Mn",
    "Iron": "Fe",
    "Cobalt": "Co",
    "Nickel": "Ni",
    "Copper": "Cu",
    "Zinc": "Zn",
    "Gallium": "Ga",
    "Germanium": "Ge",
    "Arsenic": "As",
    "Selenium": "Se",
    "Bromine": "Br",
    "Krypton": "Kr",
    "Rubidium": "Rb",
    "Strontium": "Sr",
    "Yttrium": "Y",
    "Zirconium": "Zr",
    "Niobium": "Nb",
    "Molybdenum": "Mo",
    "Technetium": "Tc",
    "Ruthenium": "Ru",
    "Rhodium": "Rh",
    "Palladium": "Pd",
    "Silver": "Ag",
    "Cadmium": "Cd",
    "Indium": "In",
    "Tin": "Sn",
    "Antimony": "Sb",
    "Tellurium": "Te",
    "Iodine": "I",
    "Xenon": "Xe",
    "Cesium": "Cs",
    "Barium": "Ba",
    "Lanthanum": "La",
    "Cerium": "Ce",
    "Praseodymium": "Pr",
    "Neodymium": "Nd",
    "Promethium": "Pm",
    "Samarium": "Sm",
    "Europium": "Eu",
    "Gadolinium": "Gd",
    "Terbium": "Tb",
    "Dysprosium": "Dy",
    "Holmium": "Ho",
    "Erbium": "Er",
    "Thulium": "Tm",
    "Ytterbium": "Yb",
    "Lutetium": "Lu",
    "Hafnium": "Hf",
    "Tantalum": "Ta",
    "Tungsten": "W",
    "Rhenium": "Re",
    "Osmium": "Os",
    "Iridium": "Ir",
    "Platinum": "Pt",
    "Gold": "Au",
    "Mercury": "Hg",
    "Thallium": "Tl",
    "Lead": "Pb",
    "Bismuth": "Bi",
    "Polonium": "Po",
    "Astatine": "At",
    "Radon": "Rn",
    "Francium": "Fr",
    "Radium": "Ra",
    "Actinium": "Ac",
    "Thorium": "Th",
    "Protactinium": "Pa",
    "Uranium": "U",
    "Neptunium": "Np",
    "Plutonium": "Pu",
    "Americium": "Am",
    "Curium": "Cm",
    "Berkelium": "Bk",
    "Californium": "Cf",
    "Einsteinium": "Es",
    "Fermium": "Fm",
    "Mendelevium": "Md",
    "Nobelium": "No",
    "Lawrencium": "Lr",
    "Rutherfordium": "Rf",
    "Dubnium": "Db",
    "Seaborgium": "Sg",
    "Bohrium": "Bh",
    "Hassium": "Hs",
    "Meitnerium": "Mt",
    "Darmstadtium": "Ds",
    "Roentgenium": "Rg",
    "Copernicium": "Cn",
    "Nihonium": "Nh",
    "Flerovium": "Fl",
    "Moscovium": "Mc",
    "Livermorium": "Lv",
    "Tennessine": "Ts",
    "Oganesson": "Og",
} # Thanks ChatGPT

symbol_elements = {symbol: element for element, symbol in element_symbols.items()} # Thanks ChatGPT